### ISSUE TITLE
How to change the classification without deleting and recreating a new box

### ISSUE THREAD

**Issue by mherrera-dsci** [linuxTown/yolo_annotation_tool#1]
I would like to reclassify and open my first classification, for example, trucks, in heavy and light trucks. It would also be good if there was an option to move the box, as in the original version. Best regards

**Comment by linuxTown** [comment]
Hi,
I can add function to move bounding boxes, but I already use right mouse button for panning the view, so for moving I need to use another button, or some king of switch mode, when some key is pressed, the right mouse button function may be switched from panning to moving bounding box, like holding down ctrl key while using right/left mouse button? Or I could use middle mouse button, by holding it down over bounding box you could move it. What do you think, the best solution would be?

**Comment by linuxTown** [comment]
Hi,
I added this functionality. Now you can move bounding boxes. To move them, hover over it, then while holding ctrl, left click on bounding box and then by moving mouse you can move it. To go back to selection mode, just release ctrl key. Let me know if it works for you or if there are any bugs.

**Comment by mherrera-dsci** [comment]
> Hi,
> I added this functionality. Now you can move bounding boxes. To move them, hover over it, then while holding ctrl, left click on bounding box and then by moving mouse you can move it. To go back to selection mode, just release ctrl key. Let me know if it works for you or if there are any bugs.

Hi,
I compiled and executed the update and it was Ok. Can you explain how the right mouse button works for panning or Zoom? I tried to right click and hold on the image and box, but I do not see pan or zoom
Ref: Ubuntu 16.04 LST, Nvidia Gforce GT 650M, 16 GB RAM
Thanks!

**Comment by linuxTown** [comment]
to zoom in use mouse scroll wheel. View panning is enabled when you are zoomed in, by holding right mouse button and dragging.
